### get
GET  http://localhost:3333/posts/posts?author=kamal&isPublished=false

### get by id
GET  http://localhost:3333/posts/19

### patch by id
PATCH   http://localhost:3333/posts/19

### create
POST http://localhost:3333/posts
Content-Type: application/json
Accept: application/json

{
    "isPublished": true,
    "title": "Overcoming Bias in Recruiting to Create a Culture of Diversity & Inclusion",
    "author": 1,
    "timestamp": 1531522701000
}